site_name: cosmic-slop-cli
repo_url: https://github.com/stirfliedlice/cosmic-slop-cli
site_url: https://stirfliedlice.github.io/cosmic-slop-cli
site_description: This is a repository for Python project cosmic-slop-cli
site_author: stirfliedlice
edit_uri: edit/main/docs/
repo_name: stirfliedlice/cosmic-slop-cli
copyright: Maintained by <a href="https://stirfliedlice.com">stirfliedlice</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/cosmic_slop_cli"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/stirfliedlice/cosmic-slop-cli
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/cosmic-slop-cli

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
